apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  namespace: netwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: netwatch/simulator:latest
          imagePullPolicy: Never  # Use local Minikube image
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: raw-events
            - name: EVENT_RATE_PER_SEC
              value: "10"
